// <auto-generated />
using System;
using GBCSportingWeb.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GBCSportingWeb.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220226153327_DateOpenedChange")]
    partial class DateOpenedChange
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("GBCSportingWeb.Models.Country", b =>
                {
                    b.Property<int>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CountryId"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CountryId");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            CountryId = 1,
                            Name = "Afghanistan"
                        },
                        new
                        {
                            CountryId = 2,
                            Name = "Albania"
                        },
                        new
                        {
                            CountryId = 3,
                            Name = "Algeria"
                        },
                        new
                        {
                            CountryId = 4,
                            Name = "Andorra"
                        },
                        new
                        {
                            CountryId = 5,
                            Name = "Angola"
                        },
                        new
                        {
                            CountryId = 6,
                            Name = "Antigua and Barbuda"
                        },
                        new
                        {
                            CountryId = 7,
                            Name = "Argentina"
                        },
                        new
                        {
                            CountryId = 8,
                            Name = "Armenia"
                        },
                        new
                        {
                            CountryId = 9,
                            Name = "Australia"
                        },
                        new
                        {
                            CountryId = 10,
                            Name = "Austria"
                        },
                        new
                        {
                            CountryId = 11,
                            Name = "Azerbaijan"
                        },
                        new
                        {
                            CountryId = 12,
                            Name = "Bahamas"
                        },
                        new
                        {
                            CountryId = 13,
                            Name = "Bahrain"
                        },
                        new
                        {
                            CountryId = 14,
                            Name = "Bangladesh"
                        },
                        new
                        {
                            CountryId = 15,
                            Name = "Barbados"
                        },
                        new
                        {
                            CountryId = 16,
                            Name = "Belarus"
                        },
                        new
                        {
                            CountryId = 17,
                            Name = "Belgium"
                        },
                        new
                        {
                            CountryId = 18,
                            Name = "Belize"
                        },
                        new
                        {
                            CountryId = 19,
                            Name = "Benin"
                        },
                        new
                        {
                            CountryId = 20,
                            Name = "Bhutan"
                        },
                        new
                        {
                            CountryId = 21,
                            Name = "Bolivia"
                        },
                        new
                        {
                            CountryId = 22,
                            Name = "Bosnia and Herzegovina"
                        },
                        new
                        {
                            CountryId = 23,
                            Name = "Botswana"
                        },
                        new
                        {
                            CountryId = 24,
                            Name = "Brazil"
                        },
                        new
                        {
                            CountryId = 25,
                            Name = "Brunei"
                        },
                        new
                        {
                            CountryId = 26,
                            Name = "Bulgaria"
                        },
                        new
                        {
                            CountryId = 27,
                            Name = "Burkina Faso"
                        },
                        new
                        {
                            CountryId = 28,
                            Name = "Burundi"
                        },
                        new
                        {
                            CountryId = 29,
                            Name = "CÃ´te d'Ivoire"
                        },
                        new
                        {
                            CountryId = 30,
                            Name = "Cabo Verde"
                        },
                        new
                        {
                            CountryId = 31,
                            Name = "Cambodia"
                        },
                        new
                        {
                            CountryId = 32,
                            Name = "Cameroon"
                        },
                        new
                        {
                            CountryId = 33,
                            Name = "Canada"
                        },
                        new
                        {
                            CountryId = 34,
                            Name = "Central African Republic"
                        },
                        new
                        {
                            CountryId = 35,
                            Name = "Chad"
                        },
                        new
                        {
                            CountryId = 36,
                            Name = "Chile"
                        },
                        new
                        {
                            CountryId = 37,
                            Name = "China"
                        },
                        new
                        {
                            CountryId = 38,
                            Name = "Colombia"
                        },
                        new
                        {
                            CountryId = 39,
                            Name = "Comoros"
                        },
                        new
                        {
                            CountryId = 40,
                            Name = "Congo (Congo-Brazzaville)"
                        },
                        new
                        {
                            CountryId = 41,
                            Name = "Costa Rica"
                        },
                        new
                        {
                            CountryId = 42,
                            Name = "Croatia"
                        },
                        new
                        {
                            CountryId = 43,
                            Name = "Cuba"
                        },
                        new
                        {
                            CountryId = 44,
                            Name = "Cyprus"
                        },
                        new
                        {
                            CountryId = 45,
                            Name = "Czechia (Czech Republic)"
                        },
                        new
                        {
                            CountryId = 46,
                            Name = "Democratic Republic of the Congo"
                        },
                        new
                        {
                            CountryId = 47,
                            Name = "Denmark"
                        },
                        new
                        {
                            CountryId = 48,
                            Name = "Djibouti"
                        },
                        new
                        {
                            CountryId = 49,
                            Name = "Dominica"
                        },
                        new
                        {
                            CountryId = 50,
                            Name = "Dominican Republic"
                        },
                        new
                        {
                            CountryId = 51,
                            Name = "Ecuador"
                        },
                        new
                        {
                            CountryId = 52,
                            Name = "Egypt"
                        },
                        new
                        {
                            CountryId = 53,
                            Name = "El Salvador"
                        },
                        new
                        {
                            CountryId = 54,
                            Name = "Equatorial Guinea"
                        },
                        new
                        {
                            CountryId = 55,
                            Name = "Eritrea"
                        },
                        new
                        {
                            CountryId = 56,
                            Name = "Estonia"
                        },
                        new
                        {
                            CountryId = 57,
                            Name = "Eswatini"
                        },
                        new
                        {
                            CountryId = 58,
                            Name = "Ethiopia"
                        },
                        new
                        {
                            CountryId = 59,
                            Name = "Fiji"
                        },
                        new
                        {
                            CountryId = 60,
                            Name = "Finland"
                        },
                        new
                        {
                            CountryId = 61,
                            Name = "France"
                        },
                        new
                        {
                            CountryId = 62,
                            Name = "Gabon"
                        },
                        new
                        {
                            CountryId = 63,
                            Name = "Gambia"
                        },
                        new
                        {
                            CountryId = 64,
                            Name = "Georgia"
                        },
                        new
                        {
                            CountryId = 65,
                            Name = "Germany"
                        },
                        new
                        {
                            CountryId = 66,
                            Name = "Ghana"
                        },
                        new
                        {
                            CountryId = 67,
                            Name = "Greece"
                        },
                        new
                        {
                            CountryId = 68,
                            Name = "Grenada"
                        },
                        new
                        {
                            CountryId = 69,
                            Name = "Guatemala"
                        },
                        new
                        {
                            CountryId = 70,
                            Name = "Guinea"
                        },
                        new
                        {
                            CountryId = 71,
                            Name = "Guinea-Bissau"
                        },
                        new
                        {
                            CountryId = 72,
                            Name = "Guyana"
                        },
                        new
                        {
                            CountryId = 73,
                            Name = "Haiti"
                        },
                        new
                        {
                            CountryId = 74,
                            Name = "Holy See"
                        },
                        new
                        {
                            CountryId = 75,
                            Name = "Honduras"
                        },
                        new
                        {
                            CountryId = 76,
                            Name = "Hungary"
                        },
                        new
                        {
                            CountryId = 77,
                            Name = "Iceland"
                        },
                        new
                        {
                            CountryId = 78,
                            Name = "India"
                        },
                        new
                        {
                            CountryId = 79,
                            Name = "Indonesia"
                        },
                        new
                        {
                            CountryId = 80,
                            Name = "Iran"
                        },
                        new
                        {
                            CountryId = 81,
                            Name = "Iraq"
                        },
                        new
                        {
                            CountryId = 82,
                            Name = "Ireland"
                        },
                        new
                        {
                            CountryId = 83,
                            Name = "Israel"
                        },
                        new
                        {
                            CountryId = 84,
                            Name = "Italy"
                        },
                        new
                        {
                            CountryId = 85,
                            Name = "Jamaica"
                        },
                        new
                        {
                            CountryId = 86,
                            Name = "Japan"
                        },
                        new
                        {
                            CountryId = 87,
                            Name = "Jordan"
                        },
                        new
                        {
                            CountryId = 88,
                            Name = "Kazakhstan"
                        },
                        new
                        {
                            CountryId = 89,
                            Name = "Kenya"
                        },
                        new
                        {
                            CountryId = 90,
                            Name = "Kiribati"
                        },
                        new
                        {
                            CountryId = 91,
                            Name = "Kuwait"
                        },
                        new
                        {
                            CountryId = 92,
                            Name = "Kyrgyzstan"
                        },
                        new
                        {
                            CountryId = 93,
                            Name = "Laos"
                        },
                        new
                        {
                            CountryId = 94,
                            Name = "Latvia"
                        },
                        new
                        {
                            CountryId = 95,
                            Name = "Lebanon"
                        },
                        new
                        {
                            CountryId = 96,
                            Name = "Lesotho"
                        },
                        new
                        {
                            CountryId = 97,
                            Name = "Liberia"
                        },
                        new
                        {
                            CountryId = 98,
                            Name = "Libya"
                        },
                        new
                        {
                            CountryId = 99,
                            Name = "Liechtenstein"
                        },
                        new
                        {
                            CountryId = 100,
                            Name = "Lithuania"
                        },
                        new
                        {
                            CountryId = 101,
                            Name = "Luxembourg"
                        },
                        new
                        {
                            CountryId = 102,
                            Name = "Madagascar"
                        },
                        new
                        {
                            CountryId = 103,
                            Name = "Malawi"
                        },
                        new
                        {
                            CountryId = 104,
                            Name = "Malaysia"
                        },
                        new
                        {
                            CountryId = 105,
                            Name = "Maldives"
                        },
                        new
                        {
                            CountryId = 106,
                            Name = "Mali"
                        },
                        new
                        {
                            CountryId = 107,
                            Name = "Malta"
                        },
                        new
                        {
                            CountryId = 108,
                            Name = "Marshall Islands"
                        },
                        new
                        {
                            CountryId = 109,
                            Name = "Mauritania"
                        },
                        new
                        {
                            CountryId = 110,
                            Name = "Mauritius"
                        },
                        new
                        {
                            CountryId = 111,
                            Name = "Mexico"
                        },
                        new
                        {
                            CountryId = 112,
                            Name = "Micronesia"
                        },
                        new
                        {
                            CountryId = 113,
                            Name = "Moldova"
                        },
                        new
                        {
                            CountryId = 114,
                            Name = "Monaco"
                        },
                        new
                        {
                            CountryId = 115,
                            Name = "Mongolia"
                        },
                        new
                        {
                            CountryId = 116,
                            Name = "Montenegro"
                        },
                        new
                        {
                            CountryId = 117,
                            Name = "Morocco"
                        },
                        new
                        {
                            CountryId = 118,
                            Name = "Mozambique"
                        },
                        new
                        {
                            CountryId = 119,
                            Name = "Myanmar (formerly Burma)"
                        },
                        new
                        {
                            CountryId = 120,
                            Name = "Namibia"
                        },
                        new
                        {
                            CountryId = 121,
                            Name = "Nauru"
                        },
                        new
                        {
                            CountryId = 122,
                            Name = "Nepal"
                        },
                        new
                        {
                            CountryId = 123,
                            Name = "Netherlands"
                        },
                        new
                        {
                            CountryId = 124,
                            Name = "New Zealand"
                        },
                        new
                        {
                            CountryId = 125,
                            Name = "Nicaragua"
                        },
                        new
                        {
                            CountryId = 126,
                            Name = "Niger"
                        },
                        new
                        {
                            CountryId = 127,
                            Name = "Nigeria"
                        },
                        new
                        {
                            CountryId = 128,
                            Name = "North Korea"
                        },
                        new
                        {
                            CountryId = 129,
                            Name = "North Macedonia"
                        },
                        new
                        {
                            CountryId = 130,
                            Name = "Norway"
                        },
                        new
                        {
                            CountryId = 131,
                            Name = "Oman"
                        },
                        new
                        {
                            CountryId = 132,
                            Name = "Pakistan"
                        },
                        new
                        {
                            CountryId = 133,
                            Name = "Palau"
                        },
                        new
                        {
                            CountryId = 134,
                            Name = "Palestine State"
                        },
                        new
                        {
                            CountryId = 135,
                            Name = "Panama"
                        },
                        new
                        {
                            CountryId = 136,
                            Name = "Papua New Guinea"
                        },
                        new
                        {
                            CountryId = 137,
                            Name = "Paraguay"
                        },
                        new
                        {
                            CountryId = 138,
                            Name = "Peru"
                        },
                        new
                        {
                            CountryId = 139,
                            Name = "Philippines"
                        },
                        new
                        {
                            CountryId = 140,
                            Name = "Poland"
                        },
                        new
                        {
                            CountryId = 141,
                            Name = "Portugal"
                        },
                        new
                        {
                            CountryId = 142,
                            Name = "Qatar"
                        },
                        new
                        {
                            CountryId = 143,
                            Name = "Romania"
                        },
                        new
                        {
                            CountryId = 144,
                            Name = "Russia"
                        },
                        new
                        {
                            CountryId = 145,
                            Name = "Rwanda"
                        },
                        new
                        {
                            CountryId = 146,
                            Name = "Saint Kitts and Nevis"
                        },
                        new
                        {
                            CountryId = 147,
                            Name = "Saint Lucia"
                        },
                        new
                        {
                            CountryId = 148,
                            Name = "Saint Vincent and the Grenadines"
                        },
                        new
                        {
                            CountryId = 149,
                            Name = "Samoa"
                        },
                        new
                        {
                            CountryId = 150,
                            Name = "San Marino"
                        },
                        new
                        {
                            CountryId = 151,
                            Name = "Sao Tome and Principe"
                        },
                        new
                        {
                            CountryId = 152,
                            Name = "Saudi Arabia"
                        },
                        new
                        {
                            CountryId = 153,
                            Name = "Senegal"
                        },
                        new
                        {
                            CountryId = 154,
                            Name = "Serbia"
                        },
                        new
                        {
                            CountryId = 155,
                            Name = "Seychelles"
                        },
                        new
                        {
                            CountryId = 156,
                            Name = "Sierra Leone"
                        },
                        new
                        {
                            CountryId = 157,
                            Name = "Singapore"
                        },
                        new
                        {
                            CountryId = 158,
                            Name = "Slovakia"
                        },
                        new
                        {
                            CountryId = 159,
                            Name = "Slovenia"
                        },
                        new
                        {
                            CountryId = 160,
                            Name = "Solomon Islands"
                        },
                        new
                        {
                            CountryId = 161,
                            Name = "Somalia"
                        },
                        new
                        {
                            CountryId = 162,
                            Name = "South Africa"
                        },
                        new
                        {
                            CountryId = 163,
                            Name = "South Korea"
                        },
                        new
                        {
                            CountryId = 164,
                            Name = "South Sudan"
                        },
                        new
                        {
                            CountryId = 165,
                            Name = "Spain"
                        },
                        new
                        {
                            CountryId = 166,
                            Name = "Sri Lanka"
                        },
                        new
                        {
                            CountryId = 167,
                            Name = "Sudan"
                        },
                        new
                        {
                            CountryId = 168,
                            Name = "Suriname"
                        },
                        new
                        {
                            CountryId = 169,
                            Name = "Sweden"
                        },
                        new
                        {
                            CountryId = 170,
                            Name = "Switzerland"
                        },
                        new
                        {
                            CountryId = 171,
                            Name = "Syria"
                        },
                        new
                        {
                            CountryId = 172,
                            Name = "Tajikistan"
                        },
                        new
                        {
                            CountryId = 173,
                            Name = "Tanzania"
                        },
                        new
                        {
                            CountryId = 174,
                            Name = "Thailand"
                        },
                        new
                        {
                            CountryId = 175,
                            Name = "Timor-Leste"
                        },
                        new
                        {
                            CountryId = 176,
                            Name = "Togo"
                        },
                        new
                        {
                            CountryId = 177,
                            Name = "Tonga"
                        },
                        new
                        {
                            CountryId = 178,
                            Name = "Trinidad and Tobago"
                        },
                        new
                        {
                            CountryId = 179,
                            Name = "Tunisia"
                        },
                        new
                        {
                            CountryId = 180,
                            Name = "Turkey"
                        },
                        new
                        {
                            CountryId = 181,
                            Name = "Turkmenistan"
                        },
                        new
                        {
                            CountryId = 182,
                            Name = "Tuvalu"
                        },
                        new
                        {
                            CountryId = 183,
                            Name = "Uganda"
                        },
                        new
                        {
                            CountryId = 184,
                            Name = "Ukraine"
                        },
                        new
                        {
                            CountryId = 185,
                            Name = "United Arab Emirates"
                        },
                        new
                        {
                            CountryId = 186,
                            Name = "United Kingdom"
                        },
                        new
                        {
                            CountryId = 187,
                            Name = "United States of America"
                        },
                        new
                        {
                            CountryId = 188,
                            Name = "Uruguay"
                        },
                        new
                        {
                            CountryId = 189,
                            Name = "Uzbekistan"
                        },
                        new
                        {
                            CountryId = 190,
                            Name = "Vanuatu"
                        },
                        new
                        {
                            CountryId = 191,
                            Name = "Venezuela"
                        },
                        new
                        {
                            CountryId = 192,
                            Name = "Vietnam"
                        },
                        new
                        {
                            CountryId = 193,
                            Name = "Yemen"
                        },
                        new
                        {
                            CountryId = 194,
                            Name = "Zambia"
                        },
                        new
                        {
                            CountryId = 195,
                            Name = "Zimbabwe"
                        });
                });

            modelBuilder.Entity("GBCSportingWeb.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerId");

                    b.HasIndex("CountryId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            Address = "203 Avenua",
                            City = "Toronto",
                            CountryId = 33,
                            Email = "Thom.Mundstock@gmail.com",
                            FirstName = "Thom",
                            LastName = "Mundstock",
                            PostalCode = "M2M 3U2",
                            State = "Ontario"
                        },
                        new
                        {
                            CustomerId = 2,
                            Address = "4th Avenue",
                            City = "NYC",
                            CountryId = 187,
                            Email = "Stanley.Tsonev@gmail.com",
                            FirstName = "Stanley",
                            LastName = "Tsonev",
                            PostalCode = "J1C 8Y1",
                            State = "New York"
                        },
                        new
                        {
                            CustomerId = 3,
                            Address = "7th Avenue",
                            City = "Tehran",
                            CountryId = 80,
                            Email = "Farshad.Jalali@gmail.com",
                            FirstName = "Farshad",
                            LastName = "Jalali",
                            PostalCode = "k1C 9T1",
                            State = "Tehran"
                        });
                });

            modelBuilder.Entity("GBCSportingWeb.Models.Incident", b =>
                {
                    b.Property<int>("IncidentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IncidentId"), 1L, 1);

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateClosed")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOpened")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int?>("TechnicianId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IncidentId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ProductId");

                    b.HasIndex("TechnicianId");

                    b.ToTable("Incidents");

                    b.HasData(
                        new
                        {
                            IncidentId = 1,
                            CustomerId = 1,
                            DateClosed = new DateTime(2022, 2, 26, 10, 33, 27, 528, DateTimeKind.Local).AddTicks(8879),
                            DateOpened = new DateTime(2022, 2, 26, 10, 33, 27, 528, DateTimeKind.Local).AddTicks(8878),
                            ProductId = 1,
                            TechnicianId = 1,
                            Title = "Problem!!"
                        },
                        new
                        {
                            IncidentId = 2,
                            CustomerId = 2,
                            DateClosed = new DateTime(2022, 2, 26, 10, 33, 27, 528, DateTimeKind.Local).AddTicks(8883),
                            DateOpened = new DateTime(2022, 2, 26, 10, 33, 27, 528, DateTimeKind.Local).AddTicks(8882),
                            ProductId = 2,
                            TechnicianId = 2,
                            Title = "Another one!!!"
                        });
                });

            modelBuilder.Entity("GBCSportingWeb.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"), 1L, 1);

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<double?>("YearlyPrice")
                        .IsRequired()
                        .HasColumnType("float");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            ProductCode = "TPYR1090",
                            ProductName = "Tournament Master 1.0",
                            ReleaseDate = new DateTime(2022, 2, 26, 10, 33, 27, 528, DateTimeKind.Local).AddTicks(8819),
                            YearlyPrice = 9.9900000000000002
                        },
                        new
                        {
                            ProductId = 2,
                            ProductCode = "WURE0115",
                            ProductName = "League Scheduler 1.0",
                            ReleaseDate = new DateTime(2022, 2, 26, 10, 33, 27, 528, DateTimeKind.Local).AddTicks(8853),
                            YearlyPrice = 50.979999999999997
                        });
                });

            modelBuilder.Entity("GBCSportingWeb.Models.Technician", b =>
                {
                    b.Property<int>("TechnicianId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TechnicianId"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TechnicianId");

                    b.ToTable("Technicians");

                    b.HasData(
                        new
                        {
                            TechnicianId = 1,
                            Email = "Sarah.Sami@georgebrown.ca",
                            Name = "Sarah Sami",
                            Phone = "4168290752"
                        },
                        new
                        {
                            TechnicianId = 2,
                            Email = "Tanja.Jamie@georgebrown.ca",
                            Name = "Tanja Jamie",
                            Phone = "4167620781"
                        });
                });

            modelBuilder.Entity("GBCSportingWeb.Models.Customer", b =>
                {
                    b.HasOne("GBCSportingWeb.Models.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("GBCSportingWeb.Models.Incident", b =>
                {
                    b.HasOne("GBCSportingWeb.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GBCSportingWeb.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GBCSportingWeb.Models.Technician", "Technician")
                        .WithMany()
                        .HasForeignKey("TechnicianId");

                    b.Navigation("Customer");

                    b.Navigation("Product");

                    b.Navigation("Technician");
                });
#pragma warning restore 612, 618
        }
    }
}
